# 命令执行 docker-compose -f docker-compose-environment.yml up -d
version: '3.9'
services:
#  # 自动加载数据
#  mysql-job-dbdata:
#    image: alpine:3.18.2
#    container_name: mysql-job-dbdata
#    volumes:
#      - /var/lib/mysql
  rabbitmq:
    image: rabbitmq:3.12.9
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    command: rabbitmq-server
    volumes:
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins

networks:
  my-network:
    driver: bridge